### ISSUE TITLE
Why there's no data repositories when I'm running ShellStarter.exe

### ISSUE THREAD

**Issue by wwwjwww** [MatteoBosco89/UnityCodeSmellAnalyzer#2]
Hi Sir/Madam,

I've encountered a problem when I'm trying to implement your tool. I downloaded UnityLint_1.0.0 and tried to experiment on your example repositories: PoorlyDesignedGame on Windows. I've run the command line as you requested:

--command line: 
.\ShellStarter.exe -d ..\\..\UnityCodeSmellAnalyzer-main\UnityCodeSmel
lAnalyzer-main\Examples\PoorlyDesignedGame\Assets -v

However, I've only got one repository: code and no data repository. And the log is as follows:
![image](https://github.com/MatteoBosco89/UnityCodeSmellAnalyzer/assets/50292531/d37efa18-4e4c-4e29-aaf2-ec59b5e01c1a)
Could you please tell me what's the problem? Thks.

**Comment by wwwjwww** [comment]
And when I tried to execute CodeSmellAnalyzer.exe, the error message shows:
Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'CommandLine, Version=2.3.1.0, Culture=neutral, PublicKeyToken=de6f01bd326f8c32' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at CodeSmellFinder.Program.Main(String[] args)

**Comment by MatteoBosco89** [comment]
Good morning, can you please update your repository to latest version and retry?

**Comment by wwwjwww** [comment]
Good Evening, Sir🌛

I have updated my repository and recompile all compilation results and tools in the same file, as well as adding the smell.txt configuration file.

However, I still got the same errors when I tried to execute ShellStarter.exe.

Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'CommandLine, Version=2.9.1.0, Culture=neutral, PublicKeyToken=5a870481e358d379' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
at Starter.Program.Main(String[] args)

**Comment by MatteoBosco89** [comment]
Try to follow this thread [here](https://stackoverflow.com/questions/42536506/could-not-load-file-or-assembly-microsoft-codeanalysis-version-1-3-1-0-cultu)

**Comment by wwwjwww** [comment]
Hi, Thanks for your guidance,

I've recompiled the repository of different tools. And each tool would produce its 'CommandLine.dll'. I've found out that each file needs its own 'CommandLine.dll' to execute or it would produce the error I stated before. So, I wonder if there's a step-by-step compilation procedure of each tool to contain the whole information in 'CommandLine.dll'.

Thks!

**Comment by wwwjwww** [comment]
Hi, I've found out that the problem is that version of CommandLine.dll in ShellStarter isn't consistent with other tools. When I changed the CommandLine version in ShellStarter.csproj to 2.3.1, then the problem is gone.
